//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace VendrSandbox.Core.Models.DocumentTypes
{
	/// <summary>Homepage</summary>
	[PublishedModel("homepage")]
	public partial class Homepage : Master, IMetaInfo, ISettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		public new const string ModelTypeAlias = "homepage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Homepage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Homepage(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Bottom Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("bottomLogo")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent BottomLogo => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("bottomLogo");

		///<summary>
		/// Copyright
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("copyright")]
		public string Copyright => this.Value<string>("copyright");

		///<summary>
		/// Facebook Pixel Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("facebookPixelCode")]
		public string FacebookPixelCode => this.Value<string>("facebookPixelCode");

		///<summary>
		/// Footer Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("footerLinks")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> FooterLinks => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link>>("footerLinks");

		///<summary>
		/// Google Site Verification Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("googleSiteVerificationCode")]
		public string GoogleSiteVerificationCode => this.Value<string>("googleSiteVerificationCode");

		///<summary>
		/// Google Tag Manager Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("googleTagManagerCode")]
		public string GoogleTagManagerCode => this.Value<string>("googleTagManagerCode");

		///<summary>
		/// Primary Navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("primaryNavigation")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent> PrimaryNavigation => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>>("primaryNavigation");

		///<summary>
		/// Store: Select the store associated with this site.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("store")]
		public global::Vendr.Core.Models.StoreReadOnly Store => this.Value<global::Vendr.Core.Models.StoreReadOnly>("store");

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("title")]
		public string Title => this.Value<string>("title");

		///<summary>
		/// Top Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("topLogo")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent TopLogo => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("topLogo");

		///<summary>
		/// SEO Settings
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("SeoSettings")]
		public global::SEOChecker.MVC.MetaData SeoSettings => global::VendrSandbox.Core.Models.DocumentTypes.MetaInfo.GetSeoSettings(this);

		///<summary>
		/// Hide Children From Navigation: Hides this page's children from the main navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("hideChildrenFromNavigation")]
		public bool HideChildrenFromNavigation => global::VendrSandbox.Core.Models.DocumentTypes.Settings.GetHideChildrenFromNavigation(this);

		///<summary>
		/// Hide From Navigation: Hides the page from the main navigation and sitemap.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.4")]
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation => global::VendrSandbox.Core.Models.DocumentTypes.Settings.GetHideFromNavigation(this);
	}
}
